### ISSUE TITLE
Padding vs Margin for column spacing

### ISSUE THREAD

**Issue by r3wt** [skeleton-framework/skeleton-framework#40]
I believe padding should be used instead of margin to "space" columns.

**Comment by gld1982ltd** [comment]
Please explain why you feel this way? I believe content should have a padding, but columns should have a margin, which is collapsible, and has no effect on the content inside the column.

**Comment by enlore** [comment]
Likewise. While I appreciate your fervor, please make a concrete case for your position. Ideally in the form of a PR demonstrating your idea.

**Comment by deviantmk** [comment]
I think its better to use margin, since, the way of how the box model works, the content will affect the padding (eg background color). Margin is on the outside, in this case it seems the right way.

**Comment by r3wt** [comment]
i'm a bit dumbfounded how the 3 of you can't see the obvious flaw in using margin over padding for containers and columns. its so obvious.

take an example where you need a container or column to consume the width of the page. not possible in skeleton, but completely possible in foundation and bootstrap since they use the box model and padding to handle the job of "spacing" columns/content. you can still use margin as needed if you want to for instance have evenly spaced columns that line up with the margins of your container.

this is my take on the matter. i quickly encountered this problem when attempting to build a full width navbar and full width sections with background color, which is not possible because of the margins.

**Comment by deviantmk** [comment]
@r3wt Im sorry maybe i am wrong but i still dont see a problem here

i think what you are asking can easily be done by adding this class to the container
```
.full {
    max-width: 100%;
    width: 100%;
}
```

**Comment by r3wt** [comment]
@deviantmk if you do that then it overflows the width of the body due to margins.

**Comment by deviantmk** [comment]
I just tried it out and i cant see any overflow

http://pasteboard.co/2PotuyMg.jpg
http://pasteboard.co/2Pou8coV.jpg
http://pasteboard.co/2PouqH3P.jpg

**Comment by enlore** [comment]
@r3wt I think I see what you're saying. I'm digging into this a bit, as it may be a useful change to the framework.

Here's a thought, though, since you're so dumbfounded by how we can't see this terribly obvious flaw. How about you take some screens of the full width navbar you tried to build to illustrate your point? You know what they say about a picture and a thousand words? Then we can stop missing the obvious flaw and you can stop being dumbfounded. Everybody wins. How nice.

Then, if you're right (which I think you actually are), you can do something even more impressive by making a pull request implementing the change you'd like to see.

**Comment by r3wt** [comment]
Well, just leave it as you see fit I suppose. I'll go do my own shit elsewhere.

**Comment by gld1982ltd** [comment]
@r3wt I don't think anyone was trying to reject you or your opinions. We are a community and we will give everyone time to comment and discuss the issue at hand. I see what you are saying as well, and @enlore is looking into it.

**Comment by deviantmk** [comment]
can someone do a code pen or something with the problem described here please

**Comment by enlore** [comment]
Ok, so check this out.

Here's how the framework currently organizes columns and rows:

<img width="1440" alt="screen shot 2016-04-08 at 10 41 20 am" src="https://cloud.githubusercontent.com/assets/3527094/14387258/9721fb7c-fd76-11e5-9078-cffbc991fe30.png">

The green border is the `body`, the blue borders are around `column` elements.

The `.row` element wrapping the columns is similarly gapped off the edge of the `body` given that our rows don't employ negative margins to pull their content out to the edges of the `container`. I just haven't given the rows an illustrative border here.

Here's how the fix would look, with the addition of a very useful `container-fluid` class: 

<img width="1440" alt="screen shot 2016-04-08 at 10 57 19 am" src="https://cloud.githubusercontent.com/assets/3527094/14387753/d1e4c13e-fd78-11e5-87d9-bb6f248f9c45.png">

`container-fluid` is the same as a regular `container` just without a max-width, if you need it.

Here's the same fix with a regular `container`. I've hovered over the row, illustrating how the column and row edges nestle up to each other, all comfy like.

<img width="1440" alt="screen shot 2016-04-08 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/3527094/14387930/9922afae-fd79-11e5-82f6-5c8166bc329c.png">

The fixed version is desirable. It makes working with backgrounds on columns, rows, and containers easy, prevents herky jerky flow issues, tidies up the math for setting the column widths, and prevents that thing that happens when an element in the layout is wider than the `body` causing a white stripe to render down edge of the whole page.

I'll work up a fix later today and submit a PR.

**Comment by gld1982ltd** [comment]
Thanks for the illustrations. Now everyone can see what needs to be done.

**Comment by enlore** [comment]
:+1:

**Comment by gld1982ltd** [comment]
Release 1.0.9
