### ISSUE TITLE
Why 1em on html instead of font-size:65%

### ISSUE THREAD

**Issue by DavidWells** [skeleton-framework/skeleton-framework#41]
Was checking out the older version of skeleton and was wondering why they use font-size:65% https://github.com/dhg/Skeleton/blob/master/css/skeleton.css#L118-L122 and this updated version used 1em https://github.com/skeleton-framework/skeleton-framework/blob/master/src/css/_base.css#L2

Why the change? Thanks!

**Comment by enlore** [comment]
That's a good question. I've seen the 65% pattern in use quite a bit and actually had to do a bit of digging to suss out a reason for it. 

As I understand it's kind of a throw back to when browsers' zooming ability was based on scaling text.  Doing 65% was a way to peg the base font size at 10px without preventing font scaling (allegedly; I haven't tested this) thereby not taking an accessibility tool away from the user. Not letting somebody zoom is pretty rude if they can't see well. 

That's not really a big deal any more since zoom is handled by scaling the whole page pixel-wise instead of just scaling the font. It's a brave new world, and you can use whatever font size you want.

As for 1em, I can say that my idea is to have Skeleton respect the default font size of the browser. I don't see the point of starting at 10px. Further, the point of Skeleton is to provide a jumping off point for your own css, so I we expect people to set their own font size.

The rest of the layout and typography css is based on that value using `rem`s, so if a given dev user does want to change the base font size of their layout, they just overwrite the `html` font size and everything should just fall in line.

Dipping into historical crap about the web always feels a little fuzzy to me so forgive me if this rationale is a bunch of hoo haa, and feel free to throw in your two cents if you know another side to the story.

**Comment by enlore** [comment]
For reference, here's a pretty decent article by Die Atwood about it: 

http://blog.codinghorror.com/the-two-types-of-browser-zoom/

**Comment by ajbraus** [comment]
I was also struck by the font size being too big imo. It just doesn't look as 'skeletal' as the 62.5%. Maybe we could compromise and set skeleton's default font size to .625rem or .75rem?

**Comment by gld1982ltd** [comment]
The point of 1em is to respect the users personal browser font settings. In upcoming versions, the font size will be configurable in the build system.
