### ISSUE TITLE
grid breakpoints

### ISSUE THREAD

**Issue by maticrivo** [skeleton-framework/skeleton-framework#50]
Is there a plan to have grid breakpoints like in bootstrap?
meaning you can have:
```
<div class="row">
  <div class="two-small five-large columns"></div>
</div>
```
so that div will take two columns on small screen and five columns on large screen

**Comment by enlore** [comment]
We actually already have that feature. Checkout the [grid system](https://github.com/skeleton-framework/skeleton-framework/blob/master/src/core/_grid.css).

Our choice of class names is similar to Bootstrap's, given that we use `xs-one`, `sm-eleven`, `md-six`. I kind of like the phrasing you've used in your example, though.

**Comment by maticrivo** [comment]
Thanks, haven't looked at the code, i couldn't find it on the documentation.

**Comment by enlore** [comment]
No prob.

Close #50

On Tue, Jun 21, 2016, 10:17 AM Matias Crivolotti <notifications@github.com>
wrote:

> Thanks, haven't looked at the code, i couldn't find it on the
> documentation.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/skeleton-framework/skeleton-framework/issues/50#issuecomment-227473296>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADXRttoBUvTo2ZMsSoKOH8UavsJW5Hwtks5qOACIgaJpZM4I60p6>
> .
>
-- 
Nick Lorenson
Dev @ HCA
m | 931 241 1014
nick@elcreativegroup.com
n.e.lorenson@gmail.com

Legal stuff: for our mutual protection, anything we send back and forth via
email is to be considered confidential unless stated otherwise.

**Comment by enlore** [comment]
Eh, I guess closing issues via email doesn't work.
