### ISSUE TITLE
font cant be loaded on dist/index.html

### ISSUE THREAD

**Issue by rafgugi** [skeleton-framework/skeleton-framework#53]
this doesnt work on my browser.
```html
<link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
```

maybe missing `http://` or `https://`?

**Comment by acrox999** [comment]
It will use the protocol that is used to load the page. If you load file directly from your PC (your index.html), it would not load because the file is loaded with just the path as referenced by Windows (e.g. C:\index.html), so it becomes C:\fonts.googleapis.com instead of http:// or https:// .

I'm not sure why they do that, however.

**Comment by enlore** [comment]
The example code that's bundled with the framework needs some updating (see #52). Thanks for pointing this out.
